stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - datasets/Extended_Employee_Performance_and_Productivity_Data.csv
    outs:
      - data/raw_data.csv   # Assuming data_ingestion.py outputs raw_data.csv

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw_data.csv
    outs:
      - data/processed_data.csv

  data_split:
    cmd: python src/data_split.py
    deps:
      - src/data_split.py
      - data/processed_data.csv
    outs:
      - datasets/train.csv
      - datasets/X_test.csv
      - datasets/y_test.csv

  model_training:
    cmd: python src/model_building.py
    deps:
      - src/model_building.py
      - datasets/train.csv
      - params.yaml
    outs:
      - models/temp/

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - datasets/X_test.csv
      - datasets/y_test.csv
      - models/temp/
    outs:
      - models/traditional/
      - metrics/eval/
