stages:
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    - datasets/Extended_Employee_Performance_and_Productivity_Data.csv
    outs:
    - data/processed_data.csv

  data_split:
    cmd: python src/data_split.py
    deps:
    - src/data_split.py
    - data/processed_data.csv
    outs:
    - datasets/train.csv
    - datasets/test.csv

  model_training:
    cmd: python src/model_building.py
    deps:
    - src/model_building.py
    - datasets/train.csv
    - params.yaml
    outs:
    - models/traditional/

  running_ann:
    cmd: python src/ann_withbackprop.py
    deps:
    - src/ann_withbackprop.py
    - datasets/train.csv
    outs:
    - models/ann_model.h5
    metrics:
    - metrics/
