models:
  RandomForestRegressor:
    n_estimators: 100
    max_depth: 5

  GradientBoostingRegressor:
    n_estimators: 100
    learning_rate: 0.1

  XGBRegressor:
    n_estimators: 100
    learning_rate: 0.1

  LGBMRegressor:
    n_estimators: 100
    learning_rate: 0.1

  CatBoostRegressor:
    iterations: 100
    learning_rate: 0.1
    depth: 3
    verbose: 0
